# Generated by Django 5.2 on 2025-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_options_blog_percentage_blog_total_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200),
        ),
    ]
