# Generated by Django 5.2 on 2025-05-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'ordering': ['is_read', 'created']},
        ),
        migrations.AddField(
            model_name='inbox',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
